name: Validate with HACS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4.2.2

      - name: HACS Action
        uses: hacs/action@2.5.0
        with:
          category: "integration"
